name: Check Rare Buses

on:
  schedule:
    - cron: '7,17,27,37,47,57 * * * *'
  workflow_dispatch:

jobs:
  check-buses:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Rare Bus Checker Script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: node check-buses.js
